UCLA scl 1.0
# Created	:	Sat Oct 18 18:17:08 2025

# User		:	placer

NumRows : 76

CoreRow Horizontal
  Coordinate     :   0
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   214
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   428
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   642
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   856
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   1070
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   1284
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   1498
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   1712
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   1926
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   2140
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   2354
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   2568
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   2782
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   2996
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   3210
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   3424
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   3638
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   3852
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   4066
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   4280
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   4494
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   4708
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   4922
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   5136
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   5350
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   5564
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   5778
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   5992
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   6206
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   6420
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   6634
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   6848
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   7062
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   7276
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   7490
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   7704
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   7918
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   8132
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   8346
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   8560
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   8774
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   8988
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   9202
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   9416
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   9630
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   9844
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   10058
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   10272
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   10486
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   10700
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   10914
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   11128
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   11342
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   11556
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   11770
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   11984
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   12198
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   12412
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   12626
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   12840
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   13054
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   13268
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   13482
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   13696
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   13910
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   14124
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   14338
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   14552
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   14766
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   14980
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   15194
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   15408
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   15622
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   15836
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
CoreRow Horizontal
  Coordinate     :   16050
  Height         :   214
  Sitewidth      :   1
  Sitespacing    :   1
  Siteorient     :   0
  Sitesymmetry   :   0
  SubrowOrigin   :   0	NumSites  :  40700
End
